export const ROUTES = {
  HOME:          "/",
  ABOUT:         "/about",
  SERVICES:      "/services",
  PRODUCTS:      "/products",
  PRODUCT:       (slug) => `/products/${slug}`,
  LOGIN:         "/login",
  REGISTER:      "/register",
  CHECKOUT:      "/checkout",
  DASHBOARD:     "/dashboard",
  PROFILE:       "/dashboard",
  EDIT_PROFILE:  "/dashboard/edit-profile",
  ORDERS:        "/dashboard/orders",
  ORDER_TRACK:   (id) => `/dashboard/orders/${id}/track`,
  INVOICES:      "/dashboard/invoices",
  SETTINGS:      "/dashboard/settings",
  ADMIN:         "/admin",
  ADMIN_PRODUCTS:"/admin/products",
  ADMIN_USERS:   "/admin/users",
  ADMIN_ORDERS:  "/admin/orders",
  ADMIN_COUPONS: "/admin/coupons",
  ADMIN_ANALYTICS:"/admin/analytics",
}
